/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VocabularyEntry = IDL.Record({
  'exampleSentence' : IDL.Text,
  'word' : IDL.Text,
  'level' : IDL.Text,
  'etymology' : IDL.Text,
  'definition' : IDL.Text,
  'partOfSpeech' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookmarkWord' : IDL.Func([IDL.Nat], [], []),
  'getBookmarkedWords' : IDL.Func([], [IDL.Vec(VocabularyEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTotalWordCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWordByIndex' : IDL.Func([IDL.Nat], [IDL.Opt(VocabularyEntry)], ['query']),
  'getWordOfTheDay' : IDL.Func([], [VocabularyEntry], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBookmark' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VocabularyEntry = IDL.Record({
    'exampleSentence' : IDL.Text,
    'word' : IDL.Text,
    'level' : IDL.Text,
    'etymology' : IDL.Text,
    'definition' : IDL.Text,
    'partOfSpeech' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookmarkWord' : IDL.Func([IDL.Nat], [], []),
    'getBookmarkedWords' : IDL.Func([], [IDL.Vec(VocabularyEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTotalWordCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWordByIndex' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(VocabularyEntry)],
        ['query'],
      ),
    'getWordOfTheDay' : IDL.Func([], [VocabularyEntry], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBookmark' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };